/**
 * Comprehensive SICP Lifecycle Enums
 */
export enum ChallengeStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_GOV_REVIEW = 'UNDER_GOV_REVIEW',
  NEEDS_MORE_INFO = 'NEEDS_MORE_INFO',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ASSIGNED_TO_UNIVERSITY = 'ASSIGNED_TO_UNIVERSITY',
  IN_RESEARCH = 'IN_RESEARCH',
  SOLUTION_PROPOSED = 'SOLUTION_PROPOSED',
  IN_PILOT = 'IN_PILOT',
  DEPLOYED = 'DEPLOYED',
  RESOLVED = 'RESOLVED',
  MERGED_INTO_SYSTEMIC = 'MERGED_INTO_SYSTEMIC',
  CLOSED = 'CLOSED',
}

export enum OrganizationType {
  UNIVERSITY = 'UNIVERSITY',
  GOVERNMENT = 'GOVERNMENT',
  INDUSTRY = 'INDUSTRY',
  STARTUP = 'STARTUP',
  MSME = 'MSME',
  CSR = 'CSR',
  RESEARCH_INSTITUTION = 'RESEARCH_INSTITUTION',
  COMMUNITY_GROUP = 'COMMUNITY_GROUP',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  INFORMATION_REQUESTED = 'INFORMATION_REQUESTED',
}

export enum AIAnalysisStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  UNAVAILABLE = 'UNAVAILABLE',
}

export enum PriorityLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum SeverityLevel {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  CATASTROPHIC = 'CATASTROPHIC',
}

export enum RelationshipType {
  DUPLICATE = 'DUPLICATE',
  RELATED = 'RELATED',
  SYSTEMIC_CHILD = 'SYSTEMIC_CHILD',
  SAME_ROOT_CAUSE = 'SAME_ROOT_CAUSE',
  SYSTEMIC_ROOT_CAUSE = 'SYSTEMIC_ROOT_CAUSE',
  RECURRING = 'RECURRING',
  DEPENDENCY = 'DEPENDENCY',
  INDEPENDENT = 'INDEPENDENT',
}

export enum RelationshipStatus {
  DETECTED = 'DETECTED',
  RECOMMENDED = 'RECOMMENDED',
  AI_RECOMMENDED = 'AI_RECOMMENDED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  MERGED = 'MERGED',
  REQUIRES_EXPERT_REVIEW = 'REQUIRES_EXPERT_REVIEW',
  REVERSED = 'REVERSED',
  EXPIRED = 'EXPIRED',
}


export enum ProjectStatus {
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  RESEARCH = 'RESEARCH',
  PROPOSAL = 'PROPOSAL',
  APPROVED = 'APPROVED',
  PROTOTYPE = 'PROTOTYPE',
  TESTING = 'TESTING',
  PILOT = 'PILOT',
  DEPLOYMENT = 'DEPLOYMENT',
  COMPLETED = 'COMPLETED',
  ON_HOLD = 'ON_HOLD',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum ProposalStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_GOV_REVIEW = 'UNDER_GOV_REVIEW',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum MilestoneStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  OVERDUE = 'OVERDUE',
}

export enum DeliverableStatus {
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REVISION_NEEDED = 'REVISION_NEEDED',
}

export enum PartnershipType {
  MENTORSHIP = 'MENTORSHIP',
  TECHNICAL_SUPPORT = 'TECHNICAL_SUPPORT',
  FUNDING = 'FUNDING',
  PROTOTYPE_SUPPORT = 'PROTOTYPE_SUPPORT',
  TESTING = 'TESTING',
  PILOT = 'PILOT',
  CSR = 'CSR',
  TECH_TRANSFER = 'TECH_TRANSFER',
}

export enum PartnershipStatus {
  PROPOSED = 'PROPOSED',
  UNDER_NEGOTIATION = 'UNDER_NEGOTIATION',
  CONFIRMED = 'CONFIRMED',
  DECLINED = 'DECLINED',
}

export enum TestStatus {
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
}

export enum PilotStatus {
  PLANNING = 'PLANNING',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  IN_PROGRESS = 'IN_PROGRESS',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_ISSUES = 'COMPLETED_WITH_ISSUES',
  IMPROVEMENT_REQUIRED = 'IMPROVEMENT_REQUIRED',
  REVISED_PILOT = 'REVISED_PILOT',
  FAILED = 'FAILED',
}

export enum OutcomeType {
  SOCIAL_IMPACT = 'SOCIAL_IMPACT',
  PROTOTYPE = 'PROTOTYPE',
  PATENT_FILED = 'PATENT_FILED',
  PATENT_GRANTED = 'PATENT_GRANTED',
  RESEARCH_PAPER = 'RESEARCH_PAPER',
  RESEARCH_PUBLICATION = 'RESEARCH_PUBLICATION',
  STARTUP = 'STARTUP',
  STARTUP_CREATED = 'STARTUP_CREATED',
  TECH_TRANSFER = 'TECH_TRANSFER',
  TECHNOLOGY_TRANSFER = 'TECHNOLOGY_TRANSFER',
  POLICY_CHANGE = 'POLICY_CHANGE',
  POLICY_ADOPTION = 'POLICY_ADOPTION',
  DEPLOYED_SOLUTION = 'DEPLOYED_SOLUTION',
  COMMERCIALIZATION = 'COMMERCIALIZATION',
  NO_INNOVATION_OUTCOME = 'NO_INNOVATION_OUTCOME',
}

export enum PrototypeStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum TestCaseStatus {
  NOT_RUN = 'NOT_RUN',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  BLOCKED = 'BLOCKED',
  WAIVED = 'WAIVED',
}

export enum DeploymentStatus {
  PLANNED = 'PLANNED',
  READY_FOR_DEPLOYMENT = 'READY_FOR_DEPLOYMENT',
  IN_PROGRESS = 'IN_PROGRESS',
  DEPLOYED = 'DEPLOYED',
  OPERATIONAL = 'OPERATIONAL',
  BLOCKED = 'BLOCKED',
  FAILED = 'FAILED',
  ROLLED_BACK = 'ROLLED_BACK',
}

export enum OutcomeVerificationStatus {
  PENDING = 'PENDING',
  EVIDENCE_COLLECTION = 'EVIDENCE_COLLECTION',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  VERIFIED_WITH_LIMITATIONS = 'VERIFIED_WITH_LIMITATIONS',
  NOT_VERIFIED = 'NOT_VERIFIED',
  FOLLOW_UP_REQUIRED = 'FOLLOW_UP_REQUIRED',
}

export enum MetricProvenance {
  VERIFIED = 'VERIFIED',
  REPORTED = 'REPORTED',
  CALCULATED = 'CALCULATED',
  ESTIMATED = 'ESTIMATED',
  AI_ASSISTED_ESTIMATE = 'AI_ASSISTED_ESTIMATE',
  UNKNOWN = 'UNKNOWN',
}

export enum CitizenProblemStatus {
  YES = 'YES',
  PARTIALLY = 'PARTIALLY',
  NO = 'NO',
  NOT_SURE = 'NOT_SURE',
}

export enum MemoryOutcomeStatus {
  SUCCESS = 'SUCCESS',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
  FAILED = 'FAILED',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW',
  SUCCESSFUL = 'SUCCESSFUL',
  PARTIALLY_EFFECTIVE = 'PARTIALLY_EFFECTIVE',
  UNDER_EVALUATION = 'UNDER_EVALUATION',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
  EFFECTIVE = 'EFFECTIVE',
  INEFFECTIVE = 'INEFFECTIVE',
  INCONCLUSIVE = 'INCONCLUSIVE',
}

export enum SolutionGuidanceVerdict {
  RECOMMEND = 'RECOMMEND',
  WARN = 'WARN',
  CAUTION = 'CAUTION',
  NO_MEMORY = 'NO_MEMORY',
}

export enum SolutionMemoryStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PUBLISHED = 'PUBLISHED',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW',
  ARCHIVED = 'ARCHIVED',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
}

export enum ReusabilityClass {
  HIGHLY_REUSABLE = 'HIGHLY_REUSABLE',
  CONDITIONALLY_REUSABLE = 'CONDITIONALLY_REUSABLE',
  REQUIRES_ADAPTATION = 'REQUIRES_ADAPTATION',
  NOT_RECOMMENDED = 'NOT_RECOMMENDED',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
}

export enum EvidenceLevel {
  VERIFIED = 'VERIFIED',
  MULTI_SOURCE_VERIFIED = 'MULTI_SOURCE_VERIFIED',
  OFFICIAL = 'OFFICIAL',
  CITIZEN_REPORTED = 'CITIZEN_REPORTED',
  CALCULATED = 'CALCULATED',
  ESTIMATED = 'ESTIMATED',
  AI_ASSISTED = 'AI_ASSISTED',
  UNKNOWN = 'UNKNOWN',
}

export enum EmbeddingStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRY_REQUIRED = 'RETRY_REQUIRED',
}

export enum TeamRole {
  LEAD_FACULTY = 'LEAD_FACULTY',
  CO_FACULTY = 'CO_FACULTY',
  STUDENT_RESEARCHER = 'STUDENT_RESEARCHER',
  INDUSTRY_MENTOR = 'INDUSTRY_MENTOR',
  SUBJECT_EXPERT = 'SUBJECT_EXPERT',
}

export enum MatchStatus {
  RECOMMENDED = 'RECOMMENDED',
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum ProblemType {
  WATER_SUPPLY = 'WATER_SUPPLY',
  ROAD_USAGE = 'ROAD_USAGE',
  HEALTHCARE_SERVICE = 'HEALTHCARE_SERVICE',
  EDUCATION_SERVICE = 'EDUCATION_SERVICE',
  ELECTRICITY_NETWORK = 'ELECTRICITY_NETWORK',
  AGRICULTURE_DEPENDENCY = 'AGRICULTURE_DEPENDENCY',
  SANITATION_SERVICE = 'SANITATION_SERVICE',
  FLOOD_ENVIRONMENTAL = 'FLOOD_ENVIRONMENTAL',
  ACCESSIBILITY_DEPENDENCY = 'ACCESSIBILITY_DEPENDENCY',
  PUBLIC_TRANSPORT_USAGE = 'PUBLIC_TRANSPORT_USAGE',
  URBAN_INFRASTRUCTURE = 'URBAN_INFRASTRUCTURE',
  UNKNOWN = 'UNKNOWN',
}

export enum ImpactMetricType {
  AFFECTED_PEOPLE = 'AFFECTED_PEOPLE',
  DAILY_ROAD_USERS = 'DAILY_ROAD_USERS',
  HOUSEHOLDS_WITHOUT_POWER = 'HOUSEHOLDS_WITHOUT_POWER',
  PATIENTS_AFFECTED = 'PATIENTS_AFFECTED',
  AFFECTED_FARMS = 'AFFECTED_FARMS',
  AFFECTED_STUDENTS = 'AFFECTED_STUDENTS',
  AFFECTED_RESIDENTS = 'AFFECTED_RESIDENTS',
  EXPOSED_POPULATION = 'EXPOSED_POPULATION',
  COMMUTERS_AFFECTED = 'COMMUTERS_AFFECTED',
  FACILITY_USERS = 'FACILITY_USERS',
  UNKNOWN_METRIC = 'UNKNOWN_METRIC',
}

export enum ImpactTimeBasis {
  TOTAL_EXPOSURE = 'TOTAL_EXPOSURE',
  PER_DAY = 'PER_DAY',
  PER_MONTH = 'PER_MONTH',
  PER_YEAR = 'PER_YEAR',
  EPISODIC = 'EPISODIC',
  CONTINUOUS = 'CONTINUOUS',
}

export enum ImpactVerificationStatus {
  VERIFIED = 'VERIFIED',
  ESTIMATED = 'ESTIMATED',
  REPORTED = 'REPORTED',
  CALCULATED = 'CALCULATED',
  AI_ASSISTED = 'AI_ASSISTED',
  UNKNOWN = 'UNKNOWN',
}

export enum InvitationStatus {
  INVITED = 'INVITED',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}

export enum FundingStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  PARTIALLY_APPROVED = 'PARTIALLY_APPROVED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  REJECTED = 'REJECTED',
}

export enum RiskSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RiskProbability {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum RiskStatus {
  IDENTIFIED = 'IDENTIFIED',
  MITIGATING = 'MITIGATING',
  RESOLVED = 'RESOLVED',
  ESCALATED = 'ESCALATED',
}

export enum FacultyAvailabilityStatus {
  AVAILABLE = 'AVAILABLE',
  COMMITTED = 'COMMITTED',
  OVERLOADED = 'OVERLOADED',
}

