import {
  SystemicIncidentDto,
  SystemicIncidentSummaryDto,
  SeverityLevel,
  SystemicIncidentStatus,
  InfrastructureNodeType,
  InfrastructureProvenance,
  InfrastructureEdgeType,
  InfrastructureImpactStatus,
  HypothesisStatus,
  SentinelProbeStatus,
  SentinelChoice,
  BranchDifferentialStatus,
  EvidenceEpistemicClass,
} from '@sicp/shared';

export const DEMO_INCIDENT_SUMMARY: SystemicIncidentSummaryDto = {
  id: 'SYS-2026-BHP-001',
  code: 'SYS-2026-001',
  title: 'Bhopal Kolar Water Supply Network — Trunk Line 4 Rupture & Contamination',
  category: 'WATER',
  status: SystemicIncidentStatus.INVESTIGATING,
  severity: SeverityLevel.SEVERE,
  evidenceStrength: 'STRONG',
  systemicScore: 0.84,
  district: 'Bhopal',
  state: 'Madhya Pradesh',
  signalCount: 4,
  leadingHypothesisTitle: 'Trunk Line 4 Joint Failure with Sub-soil Infiltration',
  leadingHypothesisScore: 68,
  isControlledDemo: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const GAMHARIA_INCIDENT_SUMMARY: SystemicIncidentSummaryDto = {
  id: 'SI-204',
  code: 'SYS-2026-JHK-204',
  title: 'Gamharia Block Multi-Village JJM Scheme — Feeder 3B-2 & Power Grid Transient Cascade',
  category: 'WATER',
  status: SystemicIncidentStatus.INVESTIGATING,
  severity: SeverityLevel.SEVERE,
  evidenceStrength: 'STRONG',
  systemicScore: 0.88,
  district: 'Seraikela Kharsawan',
  state: 'Jharkhand',
  signalCount: 25,
  leadingHypothesisTitle: 'Feeder Line 3B-2 Valve Pin Sheared Post Power-Trip Hydraulic Surge',
  leadingHypothesisScore: 84,
  isControlledDemo: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const INITIAL_DEMO_INCIDENT: SystemicIncidentDto = {
  id: 'SYS-2026-BHP-001',
  code: 'SYS-2026-001',
  title: 'Bhopal Kolar Water Supply Network — Trunk Line 4 Rupture & Contamination',
  description:
    'Systemic municipal water disruption detected across Wards 11, 12, and 13. Multi-point low pressure and turbidity reports correlate to common upstream feeder Trunk Line 4 originating from Master Balancing Reservoir 2.',
  category: 'WATER',
  status: SystemicIncidentStatus.INVESTIGATING,
  severity: SeverityLevel.SEVERE,
  evidenceStrength: 'STRONG',
  systemicScore: 0.84,
  factorBreakdown: {
    semantic: 82,
    spatial: 78,
    temporal: 92,
    symptom: 88,
    infrastructure: 95,
    rootCause: 80,
    historical: 70,
    weights: {
      semantic: 0.18,
      spatial: 0.15,
      temporal: 0.15,
      symptom: 0.18,
      infrastructure: 0.18,
      rootCause: 0.1,
      historical: 0.06,
    },
    availableFactors: ['semantic', 'spatial', 'temporal', 'symptom', 'infrastructure', 'rootCause', 'historical'],
    unavailableFactors: [],
    scoringModelVersion: 'Heuristic Evidence Assessment v1.0',
  },
  district: 'Bhopal',
  state: 'Madhya Pradesh',
  infrastructureDomain: 'WATER_DISTRIBUTION',
  canonicalChallengeId: null,
  clusterId: null,
  assignedOfficerId: 'officer-gov-01',
  assignedOfficerName: 'Er. Rajesh Varma (Executive Engineer, PHED Bhopal)',
  validatedAt: null,
  validatedById: null,
  validatedByName: null,
  validationReason: null,
  signals: [
    {
      id: 'sig-01',
      incidentId: 'SYS-2026-BHP-001',
      title: 'Severely discolored brown water and zero pressure',
      category: 'WATER',
      severity: 'SEVERE',
      district: 'Bhopal',
      state: 'Madhya Pradesh',
      latitude: 23.193,
      longitude: 77.451,
      reportedAt: new Date(Date.now() - 7200000).toISOString(),
      closestNodeId: 'node-zone-4b',
      closestNodeName: 'Service Zone 4B (Wards 12 & 13)',
      symptomSummary: 'Turbidity, low pressure, particulate matter',
    },
    {
      id: 'sig-02',
      incidentId: 'SYS-2026-BHP-001',
      title: 'Muddy water supply during morning supply cycle',
      category: 'WATER',
      severity: 'MODERATE',
      district: 'Bhopal',
      state: 'Madhya Pradesh',
      latitude: 23.196,
      longitude: 77.454,
      reportedAt: new Date(Date.now() - 6500000).toISOString(),
      closestNodeId: 'node-zone-4b',
      closestNodeName: 'Service Zone 4B (Wards 12 & 13)',
      symptomSummary: 'Muddy appearance, low pressure',
    },
    {
      id: 'sig-03',
      incidentId: 'SYS-2026-BHP-001',
      title: 'Water pressure dropped suddenly, smelling of clay',
      category: 'WATER',
      severity: 'SEVERE',
      district: 'Bhopal',
      state: 'Madhya Pradesh',
      latitude: 23.195,
      longitude: 77.439,
      reportedAt: new Date(Date.now() - 5400000).toISOString(),
      closestNodeId: 'node-bps-11',
      closestNodeName: 'Booster Pumping Station Ward 11',
      symptomSummary: 'Pressure drop, clay odor',
    },
    {
      id: 'sig-04',
      incidentId: 'SYS-2026-BHP-001',
      title: 'Tap water unusable for cooking or drinking in Sector C',
      category: 'WATER',
      severity: 'MODERATE',
      district: 'Bhopal',
      state: 'Madhya Pradesh',
      latitude: 23.201,
      longitude: 77.447,
      reportedAt: new Date(Date.now() - 4000000).toISOString(),
      closestNodeId: 'node-trunk-04',
      closestNodeName: 'Trunk Distribution Feeder Main 4',
      symptomSummary: 'Unpotable water, silt sediment',
    },
  ],
  graph: {
    incidentId: 'SYS-2026-BHP-001',
    nodes: [
      {
        id: 'node-wtp-01',
        code: 'WTP-KOLAR',
        name: 'Kolar Water Treatment Plant (150 MLD)',
        type: InfrastructureNodeType.TREATMENT_PLANT,
        category: 'WATER',
        latitude: 23.165,
        longitude: 77.405,
        district: 'Bhopal',
        state: 'Madhya Pradesh',
        capacity: '150 MLD',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Greater Bhopal South & East Zones',
        impactStatus: InfrastructureImpactStatus.POTENTIALLY_AFFECTED,
        activeSignalCount: 0,
      },
      {
        id: 'node-mbr-02',
        code: 'MBR-02',
        name: 'Master Balancing Reservoir 2 (Arera Hills)',
        type: InfrastructureNodeType.RESERVOIR,
        category: 'WATER',
        latitude: 23.218,
        longitude: 77.428,
        district: 'Bhopal',
        state: 'Madhya Pradesh',
        capacity: '45 ML Storage',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Central & South Feeder Zone',
        impactStatus: InfrastructureImpactStatus.POTENTIALLY_AFFECTED,
        activeSignalCount: 0,
      },
      {
        id: 'node-trunk-04',
        code: 'TRUNK-04',
        name: 'Trunk Distribution Feeder Main 4 (South Sector)',
        type: InfrastructureNodeType.TRUNK_LINE,
        category: 'WATER',
        latitude: 23.205,
        longitude: 77.442,
        district: 'Bhopal',
        state: 'Madhya Pradesh',
        capacity: '900mm Mild Steel',
        operationalStatus: 'DEGRADED',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Wards 11, 12, 13 Distribution Loop',
        impactStatus: InfrastructureImpactStatus.OBSERVED_AFFECTED,
        activeSignalCount: 1,
      },
      {
        id: 'node-trunk-05',
        code: 'TRUNK-05',
        name: 'Trunk Distribution Feeder Main 5 (East Sector)',
        type: InfrastructureNodeType.TRUNK_LINE,
        category: 'WATER',
        latitude: 23.235,
        longitude: 77.462,
        district: 'Bhopal',
        state: 'Madhya Pradesh',
        capacity: '750mm Ductile Iron',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Ward 14 East Sector Loop',
        impactStatus: InfrastructureImpactStatus.OBSERVED_NORMAL,
        activeSignalCount: 0,
      },
      {
        id: 'node-bps-11',
        code: 'BPS-KOLAR-11',
        name: 'Booster Pumping Station Ward 11',
        type: InfrastructureNodeType.PUMP_HOUSE,
        category: 'WATER',
        latitude: 23.195,
        longitude: 77.438,
        district: 'Bhopal',
        state: 'Madhya Pradesh',
        capacity: '3x 75kW Centrifugal Pumps',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Ward 11 Hillcrest Grid',
        impactStatus: InfrastructureImpactStatus.OBSERVED_AFFECTED,
        activeSignalCount: 1,
      },
      {
        id: 'node-zone-4b',
        code: 'ZONE-4B',
        name: 'Service Zone 4B (Wards 12 & 13 Residential Area)',
        type: InfrastructureNodeType.SERVICE_AREA,
        category: 'WATER',
        latitude: 23.192,
        longitude: 77.452,
        district: 'Bhopal',
        state: 'Madhya Pradesh',
        capacity: '14,200 Household Connections',
        operationalStatus: 'DEGRADED',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Ward 12-13 Residential',
        impactStatus: InfrastructureImpactStatus.OBSERVED_AFFECTED,
        activeSignalCount: 2,
      },
      {
        id: 'node-zone-5a',
        code: 'ZONE-5A',
        name: 'Service Zone 5A (Ward 14 East Residential Area)',
        type: InfrastructureNodeType.SERVICE_AREA,
        category: 'WATER',
        latitude: 23.242,
        longitude: 77.472,
        district: 'Bhopal',
        state: 'Madhya Pradesh',
        capacity: '11,800 Household Connections',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Ward 14 East Residential',
        impactStatus: InfrastructureImpactStatus.OBSERVED_NORMAL,
        activeSignalCount: 0,
      },
    ],
    edges: [
      {
        id: 'edge-01',
        sourceNodeId: 'node-wtp-01',
        targetNodeId: 'node-mbr-02',
        edgeType: InfrastructureEdgeType.GRAVITY_MAIN,
        capacityFlow: '150 MLD Gravity Conduit',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'MUNICIPAL_SCHEMATIC',
      },
      {
        id: 'edge-02',
        sourceNodeId: 'node-mbr-02',
        targetNodeId: 'node-trunk-04',
        edgeType: InfrastructureEdgeType.FEEDER_BRANCH,
        capacityFlow: 'Branch South (70 MLD)',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'MUNICIPAL_SCHEMATIC',
      },
      {
        id: 'edge-03',
        sourceNodeId: 'node-mbr-02',
        targetNodeId: 'node-trunk-05',
        edgeType: InfrastructureEdgeType.FEEDER_BRANCH,
        capacityFlow: 'Branch East (50 MLD)',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'MUNICIPAL_SCHEMATIC',
      },
      {
        id: 'edge-04',
        sourceNodeId: 'node-trunk-04',
        targetNodeId: 'node-bps-11',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: 'Direct Pressure Feed',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'MUNICIPAL_SCHEMATIC',
      },
      {
        id: 'edge-05',
        sourceNodeId: 'node-trunk-04',
        targetNodeId: 'node-zone-4b',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: 'Zone Sub-mains (45 MLD)',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'MUNICIPAL_SCHEMATIC',
      },
      {
        id: 'edge-06',
        sourceNodeId: 'node-trunk-05',
        targetNodeId: 'node-zone-5a',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: 'East Sub-mains (40 MLD)',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'MUNICIPAL_SCHEMATIC',
      },
    ],
    hasCycles: false,
    commonUpstreamNodes: ['node-mbr-02', 'node-wtp-01'],
    provenanceSummary: 'Municipal schematic GIS model (Bhopal Municipal Corporation)',
  },
  hypotheses: [
    {
      id: 'hyp-01',
      incidentId: 'SYS-2026-BHP-001',
      title: 'Trunk Line 4 Joint Failure with Sub-soil Infiltration',
      description:
        'Physical shear or gasket displacement along 900mm MS Feeder Main 4 causing localized pressure drop and sediment ingress during non-pumping diurnal cycles.',
      targetNodeId: 'node-trunk-04',
      targetNodeName: 'Trunk Distribution Feeder Main 4 (South Sector)',
      failureMode: 'TRUNK_LINE_FRACTURE_INFILTRATION',
      diagnosticSupportScore: 68,
      status: HypothesisStatus.LEADING_HYPOTHESIS,
      supportingEvidence: [
        {
          id: 'ev-01',
          epistemicClass: EvidenceEpistemicClass.OBSERVED,
          title: 'Cluster of 4 Citizen Reports in Wards 11-13',
          description: 'Residents report brown/turbid water and low terminal pressure at household delivery taps.',
          sourceName: 'Citizen Mobile App Reports',
          diagnosticWeight: 20,
        },
        {
          id: 'ev-02',
          epistemicClass: EvidenceEpistemicClass.COMPUTED,
          title: 'Shared Upstream Trunk Association',
          description: 'Topological analysis traces both Ward 11 and Ward 12-13 supply strictly through Trunk Line 4.',
          sourceName: 'Graph Topological Traversal',
          diagnosticWeight: 25,
        },
      ],
      contradictingEvidence: [],
      missingEvidence: [
        'Acoustic leak log verification between Ch. 2+400 and 3+100',
        'Downstream Branch B (Ward 14) comparison telemetry or sentinel confirmation',
      ],
      falsificationCriteria:
        'If Ward 14 (on Branch East) also exhibits identical contamination, root cause must be upstream at MBR-02 or Treatment Plant.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'hyp-02',
      incidentId: 'SYS-2026-BHP-001',
      title: 'Kolar Treatment Plant Filtration & Coagulant Disruption',
      description:
        'Coagulant chemical dosage shortfall or clarifier overflow at Kolar 150 MLD plant discharging elevated turbidity plant-wide.',
      targetNodeId: 'node-wtp-01',
      targetNodeName: 'Kolar Water Treatment Plant (150 MLD)',
      failureMode: 'TREATMENT_COAGULATION_FAILURE',
      diagnosticSupportScore: 45,
      status: HypothesisStatus.UNDER_EVALUATION,
      supportingEvidence: [
        {
          id: 'ev-03',
          epistemicClass: EvidenceEpistemicClass.OBSERVED,
          title: 'Turbidity in Dispatched Water',
          description: 'Coloration reported by citizens could conceptually originate at primary treatment clarifiers.',
          sourceName: 'Citizen Reports',
          diagnosticWeight: 10,
        },
      ],
      contradictingEvidence: [
        {
          id: 'ev-04',
          epistemicClass: EvidenceEpistemicClass.SOURCE_DERIVED,
          title: 'WTP SCADA Outflow Turbidity Log',
          description:
            'Plant laboratory log recorded treated water outlet turbidity at 0.8 NTU (well within 1.0 NTU BIS limit) at 06:00 AM.',
          sourceName: 'Kolar WTP Quality Log',
          diagnosticWeight: 20,
        },
      ],
      missingEvidence: ['Multi-branch differential inspection on parallel distribution trunks'],
      falsificationCriteria:
        'If any parallel feeder trunk (such as Trunk Line 5) reports clear, normal water, plant-wide treatment failure is significantly weakened.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'hyp-03',
      incidentId: 'SYS-2026-BHP-001',
      title: 'Ward 11 Booster Station Impeller Cavitation',
      description:
        'Pump seal degradation or air ingress at Ward 11 Booster Station causing hydraulic pressure disruption.',
      targetNodeId: 'node-bps-11',
      targetNodeName: 'Booster Pumping Station Ward 11',
      failureMode: 'PUMP_STATION_CAVITATION',
      diagnosticSupportScore: 35,
      status: HypothesisStatus.UNDER_EVALUATION,
      supportingEvidence: [
        {
          id: 'ev-05',
          epistemicClass: EvidenceEpistemicClass.OBSERVED,
          title: 'Low Pressure in Ward 11 Elevated Zone',
          description: 'Pressure loss is pronounced at the terminal nodes of Ward 11.',
          sourceName: 'Citizen Reports',
          diagnosticWeight: 15,
        },
      ],
      contradictingEvidence: [
        {
          id: 'ev-06',
          epistemicClass: EvidenceEpistemicClass.COMPUTED,
          title: 'Gravity Flow Inconsistency in Ward 12',
          description:
            'Ward 12 receives water by gravity from Trunk 4 without passing through the Ward 11 Booster Station, yet exhibits identical symptoms.',
          sourceName: 'Graph Topological Isolation',
          diagnosticWeight: 30,
        },
      ],
      missingEvidence: ['Booster pump current draw and suction pressure logs'],
      falsificationCriteria: 'Cannot account for contamination and pressure drop in gravity-fed Ward 12.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  sentinelProbes: [
    {
      id: 'probe-01',
      incidentId: 'SYS-2026-BHP-001',
      targetNodeId: 'node-zone-5a',
      targetNodeName: 'Service Zone 5A (Ward 14 East Residential Area)',
      serviceAreaName: 'Ward 14 East Residential (Parallel Branch)',
      inquiryTitle: 'Municipal Utility Quality Check — Ward 14 East',
      inquiryText:
        'Periodic municipal utility check: How is the tap water pressure and clarity at your premises today? Please report your direct observation.',
      status: SentinelProbeStatus.DISPATCHED,
      totalSent: 150,
      totalResponses: 0,
      responseBreakdown: {
        [SentinelChoice.NORMAL_SERVICE]: 0,
        [SentinelChoice.DEGRADED_PRESSURE]: 0,
        [SentinelChoice.CONTAMINATION_ODOR]: 0,
        [SentinelChoice.NO_SERVICE]: 0,
        [SentinelChoice.UNSURE]: 0,
      },
      branchVerificationOutcome: BranchDifferentialStatus.INSUFFICIENT_EVIDENCE,
      evidenceContributionSummary:
        'Pending community observations from Ward 14 to evaluate Branch Differential against Trunk Line 4.',
      dispatchedAt: new Date(Date.now() - 3600000).toISOString(),
      closedAt: null,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
  evidenceGaps: [
    'Acoustic pipeline correlation test along Trunk Line 4 (Ch. 2+000 to 3+500)',
    'Sentinel verification from Ward 14 (Branch East) to formally rule out Kolar Treatment Plant failure',
    'Residual chlorine test at Master Balancing Reservoir 2 outlet',
  ],
  recommendedInvestigations: [
    'Dispatch PHED leak inspection team with acoustic listening rods to Trunk Line 4',
    'Review sentinel responses from Ward 14 to verify Branch Differential',
    'Initiate University R&D proposal for acoustic pipeline leak detection and hydrodynamic modeling',
  ],
  solutionMemoryPrecedentIds: ['mem-kolar-pipeline-2024', 'mem-indore-trunk-remediation'],
  isControlledDemo: true,
  version: 1,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export function applyDemoSentinelNormal(current: SystemicIncidentDto): SystemicIncidentDto {
  const updatedProbes = current.sentinelProbes.map(p => {
    if (p.id === 'probe-01') {
      return {
        ...p,
        status: SentinelProbeStatus.CONCLUDED,
        totalResponses: (p.totalResponses || 0) + 1,
        responseBreakdown: {
          ...p.responseBreakdown,
          [SentinelChoice.NORMAL_SERVICE]: (p.responseBreakdown[SentinelChoice.NORMAL_SERVICE] || 0) + 1,
        },
        branchVerificationOutcome: BranchDifferentialStatus.BRANCH_UNAFFECTED_DISPROVED_UPSTREAM,
        evidenceContributionSummary:
          'Branch Differential Invariant active: Branch B normal service weakens upstream treatment plant hypothesis.',
      };
    }
    return p;
  });

  const updatedHypotheses = current.hypotheses.map(h => {
    if (h.id === 'hyp-01') {
      return {
        ...h,
        diagnosticSupportScore: 92,
        status: HypothesisStatus.LEADING_HYPOTHESIS,
        supportingEvidence: [
          ...h.supportingEvidence,
          {
            id: 'ev-sentinel-01',
            epistemicClass: EvidenceEpistemicClass.OBSERVED,
            title: 'Branch Differential Confirmed by Ward 14 Sentinel',
            description:
              'Ward 14 residents report clear water and normal dynamic pressure, isolating failure to Branch South (Trunk 4).',
            sourceName: 'Community Sentinel Probe Inquiry',
            diagnosticWeight: 35,
          },
        ],
      };
    }
    if (h.id === 'hyp-02') {
      return {
        ...h,
        diagnosticSupportScore: 5,
        status: HypothesisStatus.REFUTED,
        refutationReason:
          'Topologically weakened: Ward 14 on parallel branch reports normal service. Fundamental causality invariant mathematically weakens upstream treatment failure in favor of localized branch failure.',
        contradictingEvidence: [
          ...h.contradictingEvidence,
          {
            id: 'ev-sentinel-02',
            epistemicClass: EvidenceEpistemicClass.COMPUTED,
            title: 'Topological Weakening via Branch Differential Invariant',
            description:
              'Parallel branch originating from Master Balancing Reservoir 2 reports normal service. Fundamental causality invariant mathematically weakens upstream treatment failure.',
            sourceName: 'Branch Differential Analysis Engine',
            diagnosticWeight: 45,
          },
        ],
      };
    }
    return h;
  });

  return {
    ...current,
    status: SystemicIncidentStatus.INVESTIGATING,
    sentinelProbes: updatedProbes,
    hypotheses: updatedHypotheses,
    graph: {
      ...current.graph,
      branchDifferentialResult: {
        junctionNodeId: 'node-mbr-02',
        junctionNodeName: 'Master Balancing Reservoir 2 (Arera Hills)',
        affectedBranchNodeIds: ['node-trunk-04', 'node-bps-11', 'node-zone-4b'],
        normalBranchNodeIds: ['node-trunk-05', 'node-zone-5a'],
        status: BranchDifferentialStatus.BRANCH_UNAFFECTED_DISPROVED_UPSTREAM,
        deduction:
          'The new Ward 14 observation weakens the network-wide Treatment Plant hypothesis and increases support for a branch-localized Trunk Line 4 hypothesis.',
        weakenedHypothesisIds: ['hyp-02'],
        evaluatedAt: new Date().toISOString(),
      },
    },
  };
}

export const GAMHARIA_DEMO_INCIDENT: SystemicIncidentDto = {
  id: 'SYS-2026-JHK-204',
  code: 'SYS-2026-JHK-204',
  title: 'Gamharia Block Multi-Village JJM Scheme — Feeder 3B-2 & Power Grid Transient Cascade',
  description:
    'Multi-village Jal Jeevan Mission supply disruption detected across Gamharia Block (Villages 1, 2, and 3). 25 rural citizen reports document sudden loss of dynamic pressure and valve failure post-monsoon thunderstorm, correlated to feeder line 3B-2 originating from Central Overhead Service Reservoir (ESR-01).',
  category: 'WATER',
  status: SystemicIncidentStatus.INVESTIGATING,
  severity: SeverityLevel.SEVERE,
  evidenceStrength: 'STRONG',
  systemicScore: 0.88,
  factorBreakdown: {
    semantic: 85,
    spatial: 80,
    temporal: 94,
    symptom: 90,
    infrastructure: 96,
    rootCause: 84,
    historical: 75,
    weights: {
      semantic: 0.18,
      spatial: 0.15,
      temporal: 0.15,
      symptom: 0.18,
      infrastructure: 0.18,
      rootCause: 0.1,
      historical: 0.06,
    },
    availableFactors: ['semantic', 'spatial', 'temporal', 'symptom', 'infrastructure', 'rootCause', 'historical'],
    unavailableFactors: [],
    scoringModelVersion: 'Heuristic Evidence Assessment v1.0',
  },
  district: 'Seraikela Kharsawan',
  state: 'Jharkhand',
  infrastructureDomain: 'RURAL_JJM_DISTRIBUTION',
  canonicalChallengeId: null,
  clusterId: null,
  assignedOfficerId: 'officer-gov-jh-01',
  assignedOfficerName: 'Er. Alok Ranjan (Superintending Engineer, DW&SD Jharkhand)',
  validatedAt: null,
  validatedById: null,
  validatedByName: null,
  validationReason: null,
  signals: [
    {
      id: 'sig-jh-01',
      incidentId: 'SYS-2026-JHK-204',
      title: 'Complete tap dry-out across Village 1 after evening power spike',
      category: 'WATER',
      severity: 'SEVERE',
      district: 'Seraikela Kharsawan',
      state: 'Jharkhand',
      latitude: 22.812,
      longitude: 86.082,
      reportedAt: new Date(Date.now() - 7200000).toISOString(),
      closestNodeId: 'node-jh-v1',
      closestNodeName: 'Gamharia Village 1 Terminal Standposts',
      symptomSummary: 'No water supply, dry standpost',
    },
    {
      id: 'sig-jh-02',
      incidentId: 'SYS-2026-JHK-204',
      title: 'No water at school JJM connection in Village 2',
      category: 'WATER',
      severity: 'SEVERE',
      district: 'Seraikela Kharsawan',
      state: 'Jharkhand',
      latitude: 22.819,
      longitude: 86.088,
      reportedAt: new Date(Date.now() - 6500000).toISOString(),
      closestNodeId: 'node-jh-v2',
      closestNodeName: 'Gamharia Village 2 Terminal Standposts',
      symptomSummary: 'No flow, audible air suction in pipe',
    },
    {
      id: 'sig-jh-03',
      incidentId: 'SYS-2026-JHK-204',
      title: 'Trickle pressure only at community borehole backup in Village 3',
      category: 'WATER',
      severity: 'MODERATE',
      district: 'Seraikela Kharsawan',
      state: 'Jharkhand',
      latitude: 22.825,
      longitude: 86.094,
      reportedAt: new Date(Date.now() - 5400000).toISOString(),
      closestNodeId: 'node-jh-v3',
      closestNodeName: 'Gamharia Village 3 Terminal Standposts',
      symptomSummary: 'Low flow, brown discoloration',
    },
    {
      id: 'sig-jh-04',
      incidentId: 'SYS-2026-JHK-204',
      title: 'Rumble heard near sluice valve 3B-2 housing during thunderstorm',
      category: 'WATER',
      severity: 'SEVERE',
      district: 'Seraikela Kharsawan',
      state: 'Jharkhand',
      latitude: 22.815,
      longitude: 86.085,
      reportedAt: new Date(Date.now() - 4000000).toISOString(),
      closestNodeId: 'node-jh-valve3b2',
      closestNodeName: 'Motorized Sluice Valve 3B-2',
      symptomSummary: 'Mechanical vibration, valve chamber leak',
    },
  ],
  graph: {
    incidentId: 'SYS-2026-JHK-204',
    nodes: [
      {
        id: 'node-jh-intake',
        code: 'WTP-SUBARNAREKHA',
        name: 'Subarnarekha River Intake & WTP (50 MLD)',
        type: InfrastructureNodeType.TREATMENT_PLANT,
        category: 'WATER',
        latitude: 22.785,
        longitude: 86.052,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '50 MLD',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Gamharia Rural Block Zone',
        impactStatus: InfrastructureImpactStatus.POTENTIALLY_AFFECTED,
        activeSignalCount: 0,
      },
      {
        id: 'node-jh-esr01',
        code: 'ESR-CENTRAL-01',
        name: 'Elevated Service Reservoir ESR-01 (Gamharia Central)',
        type: InfrastructureNodeType.RESERVOIR,
        category: 'WATER',
        latitude: 22.802,
        longitude: 86.068,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '2.5 ML',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Gamharia Multi-Village Grid',
        impactStatus: InfrastructureImpactStatus.POTENTIALLY_AFFECTED,
        activeSignalCount: 0,
      },
      {
        id: 'node-jh-feeder3b',
        code: 'FEEDER-3B',
        name: 'Rural Feeder Main 3B (East Sector)',
        type: InfrastructureNodeType.TRUNK_LINE,
        category: 'WATER',
        latitude: 22.809,
        longitude: 86.076,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '400 mm DI',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Villages 1, 2, 3 Cluster',
        impactStatus: InfrastructureImpactStatus.ROOT_CAUSE_CANDIDATE,
        activeSignalCount: 1,
      },
      {
        id: 'node-jh-valve3b2',
        code: 'VALVE-3B-2',
        name: 'Motorized Sluice Valve 3B-2 (Village Cluster)',
        type: InfrastructureNodeType.VALVE,
        category: 'WATER',
        latitude: 22.815,
        longitude: 86.085,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '300 mm Motorized',
        operationalStatus: 'DEGRADED',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Villages 1-3 Inflow Junction',
        impactStatus: InfrastructureImpactStatus.OBSERVED_AFFECTED,
        activeSignalCount: 1,
      },
      {
        id: 'node-jh-v1',
        code: 'ZONE-VILLAGE-01',
        name: 'Gamharia Village 1 Terminal Standposts',
        type: InfrastructureNodeType.SERVICE_AREA,
        category: 'WATER',
        latitude: 22.812,
        longitude: 86.082,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '1,800 Residents',
        operationalStatus: 'DEGRADED',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Gamharia Village 1 Habitation',
        impactStatus: InfrastructureImpactStatus.OBSERVED_AFFECTED,
        activeSignalCount: 1,
      },
      {
        id: 'node-jh-v2',
        code: 'ZONE-VILLAGE-02',
        name: 'Gamharia Village 2 Terminal Standposts',
        type: InfrastructureNodeType.SERVICE_AREA,
        category: 'WATER',
        latitude: 22.819,
        longitude: 86.088,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '2,400 Residents',
        operationalStatus: 'DEGRADED',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Gamharia Village 2 Habitation',
        impactStatus: InfrastructureImpactStatus.OBSERVED_AFFECTED,
        activeSignalCount: 1,
      },
      {
        id: 'node-jh-v3',
        code: 'ZONE-VILLAGE-03',
        name: 'Gamharia Village 3 Terminal Standposts',
        type: InfrastructureNodeType.SERVICE_AREA,
        category: 'WATER',
        latitude: 22.825,
        longitude: 86.094,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '1,500 Residents',
        operationalStatus: 'DEGRADED',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Gamharia Village 3 Habitation',
        impactStatus: InfrastructureImpactStatus.OBSERVED_AFFECTED,
        activeSignalCount: 1,
      },
      {
        id: 'node-jh-feeder3a',
        code: 'FEEDER-3A',
        name: 'Rural Feeder Main 3A (North Control Sector)',
        type: InfrastructureNodeType.DISTRIBUTION_LINE,
        category: 'WATER',
        latitude: 22.805,
        longitude: 86.062,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '350 mm DI',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Gamharia Village 4 Control Sector',
        impactStatus: InfrastructureImpactStatus.POTENTIALLY_AFFECTED,
        activeSignalCount: 0,
      },
      {
        id: 'node-jh-v4',
        code: 'ZONE-VILLAGE-04',
        name: 'Gamharia Village 4 Standposts (Parallel Branch)',
        type: InfrastructureNodeType.SERVICE_AREA,
        category: 'WATER',
        latitude: 22.808,
        longitude: 86.059,
        district: 'Seraikela Kharsawan',
        state: 'Jharkhand',
        capacity: '2,100 Residents',
        operationalStatus: 'OPERATIONAL',
        provenance: InfrastructureProvenance.CONTROLLED_DEMO,
        serviceAreaName: 'Gamharia Village 4 Control Habitation',
        impactStatus: InfrastructureImpactStatus.POTENTIALLY_AFFECTED,
        activeSignalCount: 0,
      },
    ],
    edges: [
      {
        id: 'edge-jh-01',
        sourceNodeId: 'node-jh-intake',
        targetNodeId: 'node-jh-esr01',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: '35 MLD Raw Pumping Main',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'CONTROLLED_DEMO',
      },
      {
        id: 'edge-jh-02',
        sourceNodeId: 'node-jh-esr01',
        targetNodeId: 'node-jh-feeder3b',
        edgeType: InfrastructureEdgeType.FEEDER_BRANCH,
        capacityFlow: 'Feeder Main 3B (18 MLD)',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'CONTROLLED_DEMO',
      },
      {
        id: 'edge-jh-03',
        sourceNodeId: 'node-jh-esr01',
        targetNodeId: 'node-jh-feeder3a',
        edgeType: InfrastructureEdgeType.FEEDER_BRANCH,
        capacityFlow: 'Feeder Main 3A (17 MLD)',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'CONTROLLED_DEMO',
      },
      {
        id: 'edge-jh-04',
        sourceNodeId: 'node-jh-feeder3b',
        targetNodeId: 'node-jh-valve3b2',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: 'Feeder Sub-branch (12 MLD)',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'CONTROLLED_DEMO',
      },
      {
        id: 'edge-jh-05',
        sourceNodeId: 'node-jh-valve3b2',
        targetNodeId: 'node-jh-v1',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: 'Village 1 Habitation Main',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'CONTROLLED_DEMO',
      },
      {
        id: 'edge-jh-06',
        sourceNodeId: 'node-jh-valve3b2',
        targetNodeId: 'node-jh-v2',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: 'Village 2 Habitation Main',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'CONTROLLED_DEMO',
      },
      {
        id: 'edge-jh-07',
        sourceNodeId: 'node-jh-valve3b2',
        targetNodeId: 'node-jh-v3',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: 'Village 3 Habitation Main',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'CONTROLLED_DEMO',
      },
      {
        id: 'edge-jh-08',
        sourceNodeId: 'node-jh-feeder3a',
        targetNodeId: 'node-jh-v4',
        edgeType: InfrastructureEdgeType.FLOW_SUPPLY,
        capacityFlow: 'Village 4 Parallel Habitation Main',
        bidirectional: false,
        status: 'ACTIVE',
        provenance: 'CONTROLLED_DEMO',
      },
    ],
    hasCycles: false,
    commonUpstreamNodes: ['node-jh-esr01'],
    provenanceSummary: 'JJM Rural Water Infrastructure Schematic (Gamharia, Seraikela Kharsawan)',
    branchDifferentialResult: null,
  },
  hypotheses: [
    {
      id: 'hyp-jh-01',
      incidentId: 'SYS-2026-JHK-204',
      title: 'Feeder Line 3B-2 Valve Pin Sheared Post Power-Trip Hydraulic Surge',
      description:
        'A sudden rural 11kV grid outage caused backflow slam pressure waves, shearing the mechanical drive pin on Motorized Sluice Valve 3B-2 and leaving it stuck in closed position.',
      failureMode: 'VALVE_MECHANICAL_DRIVE_PIN_SHEAR',
      status: HypothesisStatus.LEADING_HYPOTHESIS,
      diagnosticSupportScore: 84,
      targetNodeId: 'node-jh-valve3b2',
      targetNodeName: 'Motorized Sluice Valve 3B-2',
      supportingEvidence: [
        {
          id: 'ev-jh-01',
          epistemicClass: EvidenceEpistemicClass.OBSERVED,
          title: 'Citizen Report of Mechanical Clank at Valve Chamber',
          description: 'Villagers reported loud metallic sound and sudden cut-off of standpost supply.',
          sourceName: 'Citizen Grievance #CR-JH-1842',
          diagnosticWeight: 40,
        },
        {
          id: 'ev-jh-02',
          epistemicClass: EvidenceEpistemicClass.COMPUTED,
          title: 'All Disruption Signals Cluster Downstream of Valve 3B-2',
          description: 'Villages 1, 2, and 3 are fed solely through Valve 3B-2 and all experienced simultaneous zero supply.',
          sourceName: 'Geospatial Lineage Analysis',
          diagnosticWeight: 35,
        },
      ],
      contradictingEvidence: [],
      missingEvidence: [
        'Manual inspection of valve stem position and gearbox torque',
        'Pressure logger reading immediately downstream of Valve 3B-2',
      ],
      falsificationCriteria:
        'If Village 4 (on parallel Feeder 3A) also experiences pressure failure, the issue is upstream at ESR-01 or the River Intake, falsifying this localized hypothesis.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'hyp-jh-02',
      incidentId: 'SYS-2026-JHK-204',
      title: 'Subarnarekha River Intake Pump Trip / River Sedimentation',
      description:
        'River intake pumps tripped during thunderstorm power transient, starving the central ESR reservoir and halting gravity supply.',
      failureMode: 'RIVER_INTAKE_PUMP_TRIP_SEDIMENTATION',
      status: HypothesisStatus.UNDER_EVALUATION,
      diagnosticSupportScore: 42,
      targetNodeId: 'node-jh-intake',
      targetNodeName: 'Subarnarekha River Intake & WTP',
      supportingEvidence: [
        {
          id: 'ev-jh-03',
          epistemicClass: EvidenceEpistemicClass.SOURCE_DERIVED,
          title: '11kV Rural Feeder Power Trip Logged at 17:42',
          description: 'Discom SCADA recorded momentary 4-minute voltage dip on rural feeder grid.',
          sourceName: 'JBVNL Power Discom SCADA',
          diagnosticWeight: 25,
        },
      ],
      contradictingEvidence: [
        {
          id: 'ev-jh-04',
          epistemicClass: EvidenceEpistemicClass.SOURCE_DERIVED,
          title: 'ESR-01 Water Level Sensor Verified at 78% Capacity',
          description: 'Central reservoir holds 1.95 ML of treated water, sufficient for 14 hours of continuous gravity distribution.',
          sourceName: 'JJM SCADA Level Telemetry',
          diagnosticWeight: 35,
        },
      ],
      missingEvidence: ['Raw water intake turbidity logs during storm peak'],
      falsificationCriteria: 'Sustained water level in ESR-01 disproves complete intake starvation.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'hyp-jh-03',
      incidentId: 'SYS-2026-JHK-204',
      title: 'Power Grid Transient Inverter Burnout at ESR Central',
      description:
        'Surge lightning damaged control relays at the central elevated reservoir, inhibiting automated branch distribution.',
      failureMode: 'POWER_GRID_INVERTER_BURNOUT',
      status: HypothesisStatus.UNDER_EVALUATION,
      diagnosticSupportScore: 28,
      targetNodeId: 'node-jh-esr01',
      targetNodeName: 'Elevated Service Reservoir ESR-01',
      supportingEvidence: [],
      contradictingEvidence: [],
      missingEvidence: ['Physical relay cabinet multimeter readings'],
      falsificationCriteria: 'Parallel gravity feeder lines operate passively without electrical actuator dependency.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  sentinelProbes: [
    {
      id: 'probe-jh-01',
      incidentId: 'SYS-2026-JHK-204',
      targetNodeId: 'node-jh-v4',
      targetNodeName: 'Gamharia Village 4 Standposts (Parallel Branch)',
      serviceAreaName: 'Gamharia Village 4 Control Habitation',
      inquiryTitle: 'Municipal Utility Quality Check — Gamharia Village 4',
      inquiryText:
        'Periodic municipal utility check: How is the tap water pressure and clarity at your premises today? Please report your direct observation.',
      status: SentinelProbeStatus.DISPATCHED,
      totalSent: 120,
      totalResponses: 0,
      responseBreakdown: {
        [SentinelChoice.NORMAL_SERVICE]: 0,
        [SentinelChoice.DEGRADED_PRESSURE]: 0,
        [SentinelChoice.CONTAMINATION_ODOR]: 0,
        [SentinelChoice.NO_SERVICE]: 0,
        [SentinelChoice.UNSURE]: 0,
      },
      branchVerificationOutcome: BranchDifferentialStatus.INSUFFICIENT_EVIDENCE,
      evidenceContributionSummary:
        'Pending community observations from Gamharia Village 4 to evaluate Branch Differential against Feeder 3B-2.',
      dispatchedAt: new Date(Date.now() - 3600000).toISOString(),
      closedAt: null,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
  evidenceGaps: [
    'Acoustic listening rod verification along Feeder 3B-2 valve chamber',
    'Sentinel verification from Village 4 on Feeder 3A to isolate network branch differential',
    'Relay trip logs from JBVNL Gamharia sub-station',
  ],
  recommendedInvestigations: [
    'Dispatch DW&SD field technician to inspect mechanical actuator on Valve 3B-2',
    'Review Village 4 sentinel feedback to confirm normal pressure on parallel feeder',
    'Initiate University research challenge for rural smart water-hammer arrestor systems',
  ],
  solutionMemoryPrecedentIds: ['mem-ranchi-rural-jjm-2023'],
  isControlledDemo: true,
  version: 1,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export function applyGamhariaSentinelNormal(current: SystemicIncidentDto): SystemicIncidentDto {
  const updatedProbes = current.sentinelProbes.map(p => {
    if (p.id === 'probe-jh-01') {
      return {
        ...p,
        status: SentinelProbeStatus.CONCLUDED,
        totalResponses: (p.totalResponses || 0) + 1,
        responseBreakdown: {
          ...p.responseBreakdown,
          [SentinelChoice.NORMAL_SERVICE]: (p.responseBreakdown[SentinelChoice.NORMAL_SERVICE] || 0) + 1,
        },
        branchVerificationOutcome: BranchDifferentialStatus.BRANCH_UNAFFECTED_DISPROVED_UPSTREAM,
        evidenceContributionSummary:
          'Branch Differential Invariant active: Village 4 normal service on Feeder 3A weakens Subarnarekha river intake outage hypothesis.',
      };
    }
    return p;
  });

  const updatedHypotheses = current.hypotheses.map(h => {
    if (h.id === 'hyp-jh-01') {
      return {
        ...h,
        diagnosticSupportScore: 95,
        status: HypothesisStatus.LEADING_HYPOTHESIS,
        supportingEvidence: [
          ...h.supportingEvidence,
          {
            id: 'ev-jh-sentinel-01',
            epistemicClass: EvidenceEpistemicClass.OBSERVED,
            title: 'Branch Differential Confirmed by Village 4 Sentinel',
            description:
              'Village 4 residents report steady dynamic pressure from Feeder 3A, isolating failure to Feeder 3B-2 valve assembly.',
            sourceName: 'Community Sentinel Probe Inquiry',
            diagnosticWeight: 35,
          },
        ],
      };
    }
    if (h.id === 'hyp-jh-02') {
      return {
        ...h,
        diagnosticSupportScore: 4,
        status: HypothesisStatus.REFUTED,
        refutationReason:
          'Topologically weakened: Village 4 on parallel Feeder 3A reports normal service from ESR-01. Fundamental causality invariant weakens upstream intake failure.',
        contradictingEvidence: [
          ...h.contradictingEvidence,
          {
            id: 'ev-jh-sentinel-02',
            epistemicClass: EvidenceEpistemicClass.COMPUTED,
            title: 'Topological Weakening via Branch Differential Invariant',
            description:
              'Parallel branch originating from ESR-01 reports normal service. Fundamental causality invariant mathematically weakens upstream intake failure.',
            sourceName: 'Branch Differential Analysis Engine',
            diagnosticWeight: 45,
          },
        ],
      };
    }
    return h;
  });

  return {
    ...current,
    status: SystemicIncidentStatus.INVESTIGATING,
    sentinelProbes: updatedProbes,
    hypotheses: updatedHypotheses,
    graph: {
      ...current.graph,
      branchDifferentialResult: {
        junctionNodeId: 'node-jh-esr01',
        junctionNodeName: 'Elevated Service Reservoir ESR-01 (Gamharia Central)',
        affectedBranchNodeIds: ['node-jh-feeder3b', 'node-jh-valve3b2', 'node-jh-v1', 'node-jh-v2', 'node-jh-v3'],
        normalBranchNodeIds: ['node-jh-feeder3a', 'node-jh-v4'],
        status: BranchDifferentialStatus.BRANCH_UNAFFECTED_DISPROVED_UPSTREAM,
        deduction:
          'The new Gamharia Village 4 observation weakens the network-wide Subarnarekha River Intake hypothesis and increases support for a feeder-localized Line 3B-2 valve failure.',
        weakenedHypothesisIds: ['hyp-jh-02'],
        evaluatedAt: new Date().toISOString(),
      },
    },
  };
}
